/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Surtidor.h"
#include "LCD_1.h"
#include "Impresora.h"
#include "PC.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "IB2_aliases.h"
#include "IB2.h"
#include "isr_1.h"
#include "Timer_RxSurtidor.h"
#include "LCD_2.h"
#include "Clock_1.h"
#include "IB1_aliases.h"
#include "IB1.h"
#include "Pin_WP_aliases.h"
#include "Pin_WP.h"
#include "timer_clock_1.h"
#include "Timer_Animacion.h"
#include "isr_5.h"
#include "Timer_Modo.h"
#include "isr_4.h"
#include "isr_3.h"
#include "Timer_Animacion2.h"
#include "EEPROM.h"
#include "LP.h"
#include "LCD_1_IntClock.h"
#include "PC_IntClock.h"
#include "LCD_2_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

